#include "TFile.h"
#include "TTree.h"
#include "TSystem.h"

#include <iostream>

void skim_tree() {
// Example of Root macro to copy a subset of a Tree to a new Tree
// Only selected entries are copied to the new Tree.
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 99 1
//Author: Rene Brun

   gSystem->Load("$ROOTSYS/test/libEvent");

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile("inputs/CoordFiltered16.root");
   TTree *oldtree = (TTree*)oldfile->Get("StripCoords");
   Long64_t nentries = oldtree->GetEntries();
  Int_t           layer, module, ladder, strip, segment;
  Float_t         x, y, z;
  TBranch        *b_layer;   //!
  TBranch        *b_module;   //!
  TBranch        *b_ladder;   //!
  TBranch        *b_strip;   //!
  TBranch        *b_segment;   //!
  TBranch        *b_x;   //!
  TBranch        *b_y;   //!
  TBranch        *b_z;   //!

  oldtree->SetBranchAddress("layer", &layer, &b_layer);
  oldtree->SetBranchAddress("module", &module, &b_module);
  oldtree->SetBranchAddress("ladder", &ladder, &b_ladder);
  oldtree->SetBranchAddress("strip", &strip, &b_strip);
  oldtree->SetBranchAddress("segment", &segment, &b_segment);
  oldtree->SetBranchAddress("x", &x, &b_x);
  oldtree->SetBranchAddress("y", &y, &b_y);
  oldtree->SetBranchAddress("z", &z, &b_z);

   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile("inputs/CoordFiltered16_layer5.root","recreate");
   TTree *newtree = oldtree->CloneTree(0);

   for (Long64_t i=0;i<nentries; i++) {
     if (i%10000 == 0) std::cout << i << " / " << nentries << std::endl;
      oldtree->GetEntry(i);
      if (layer == 5) newtree->Fill();
   }
   newtree->Print();
   newtree->AutoSave();
   delete oldfile;
   delete newfile;
}
